#NAME: Robathan Harries
#ID: 904836501
#EMAIL: r0b@ucla.edu
#SLIPDAYS: 0

dist: my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README
	tar -czvf lab4a-904836501.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README

all: dist

clean:
	rm lab4a-904836501.tar.gz
